// Generated by tools/sdkgen from the connector manifests built into taskiem.
// Do not edit: run `go generate ./sdk` instead.

import { connector, type ConnectorExtra, type StepSpec, type Val, type Value } from "./builder.js";

// Dojah (dojah@1)
export interface DojahCheckBalanceInput {
  [key: string]: Value;
}
export interface DojahLookupBvnInput {
  bvn: Val<string>;
  /** The photo is large and personal; omitted unless asked for */
  include_image?: Val<boolean>;
}
export interface DojahLookupNinInput {
  nin: Val<string>;
}
export const dojah = {
  /** Check wallet balance (read) */
  check_balance: (input?: DojahCheckBalanceInput, extra?: ConnectorExtra): StepSpec => connector("dojah@1", "check_balance", input, extra),
  /** Look up BVN (read) */
  lookup_bvn: (input: DojahLookupBvnInput, extra?: ConnectorExtra): StepSpec => connector("dojah@1", "lookup_bvn", input, extra),
  /** Look up NIN (read) */
  lookup_nin: (input: DojahLookupNinInput, extra?: ConnectorExtra): StepSpec => connector("dojah@1", "lookup_nin", input, extra),
};

// iswallet (iswallet@1)
export interface IswalletGetBalanceInput {
  wallet_id: Val<string>;
}
export interface IswalletGetPayoutInput {
  outflow_id: Val<string>;
}
export interface IswalletListBanksInput {
  [key: string]: Value;
}
export interface IswalletNameEnquiryInput {
  account_number: Val<string>;
  bank_code: Val<string>;
}
export interface IswalletPayoutInput {
  /** As returned by name_enquiry */
  account_name: Val<string>;
  account_number: Val<string>;
  /** Kobo */
  amount: Val<number>;
  /** From list_banks */
  bank_code: Val<string>;
  /** Echoed back on reads */
  metadata?: Value;
  narration?: Val<string>;
  wallet_id: Val<string>;
}
export interface IswalletTransferInput {
  /** Minor units (kobo for NGN) */
  amount: Val<number>;
  currency?: Val<string>;
  from_wallet_id: Val<string>;
  narration?: Val<string>;
  to_wallet_id: Val<string>;
}
export const iswallet = {
  /** Get wallet balance (read) */
  get_balance: (input: IswalletGetBalanceInput, extra?: ConnectorExtra): StepSpec => connector("iswallet@1", "get_balance", input, extra),
  /** Get payout status (read) */
  get_payout: (input: IswalletGetPayoutInput, extra?: ConnectorExtra): StepSpec => connector("iswallet@1", "get_payout", input, extra),
  /** List banks (read) */
  list_banks: (input?: IswalletListBanksInput, extra?: ConnectorExtra): StepSpec => connector("iswallet@1", "list_banks", input, extra),
  /** Resolve account name (read) */
  name_enquiry: (input: IswalletNameEnquiryInput, extra?: ConnectorExtra): StepSpec => connector("iswallet@1", "name_enquiry", input, extra),
  /** Pay out to a bank account (idempotent_write) */
  payout: (input: IswalletPayoutInput, extra?: ConnectorExtra): StepSpec => connector("iswallet@1", "payout", input, extra),
  /** Transfer between wallets (idempotent_write) */
  transfer: (input: IswalletTransferInput, extra?: ConnectorExtra): StepSpec => connector("iswallet@1", "transfer", input, extra),
};

// Paystack (paystack@1)
export interface PaystackCheckBalanceInput {
  [key: string]: Value;
}
export interface PaystackTransferInput {
  /** Amount in kobo */
  amount: Val<number>;
  currency?: Val<string>;
  reason?: Val<string>;
  /** Recipient code */
  recipient: Val<string>;
}
export interface PaystackVerifyChargeInput {
  reference: Val<string>;
}
export interface PaystackVerifyTransferInput {
  reference: Val<string>;
}
export const paystack = {
  /** Check balance (read) */
  check_balance: (input?: PaystackCheckBalanceInput, extra?: ConnectorExtra): StepSpec => connector("paystack@1", "check_balance", input, extra),
  /** Send transfer (idempotent_write) */
  transfer: (input: PaystackTransferInput, extra?: ConnectorExtra): StepSpec => connector("paystack@1", "transfer", input, extra),
  /** Verify charge (read) */
  verify_charge: (input: PaystackVerifyChargeInput, extra?: ConnectorExtra): StepSpec => connector("paystack@1", "verify_charge", input, extra),
  /** Verify transfer (read) */
  verify_transfer: (input: PaystackVerifyTransferInput, extra?: ConnectorExtra): StepSpec => connector("paystack@1", "verify_transfer", input, extra),
};

// PostgreSQL (postgres@1)
export interface PostgresExecuteInput {
  params?: Value;
  sql: Val<string>;
}
export interface PostgresQueryInput {
  max_rows?: Val<number>;
  params?: Value;
  sql: Val<string>;
}
export const postgres = {
  /** Run a statement that changes data (unsafe_write) */
  execute: (input: PostgresExecuteInput, extra?: ConnectorExtra): StepSpec => connector("postgres@1", "execute", input, extra),
  /** Run a read-only query (read) */
  query: (input: PostgresQueryInput, extra?: ConnectorExtra): StepSpec => connector("postgres@1", "query", input, extra),
};

// Termii (termii@1)
export interface TermiiCheckBalanceInput {
  [key: string]: Value;
}
export interface TermiiSendSmsInput {
  channel?: Val<"generic" | "dnd" | "whatsapp">;
  /** Sender ID; defaults to the connection's sender_id */
  from?: Val<string>;
  sms: Val<string>;
  /** Recipient in international format without + */
  to: Val<string>;
}
export const termii = {
  /** Check balance (read) */
  check_balance: (input?: TermiiCheckBalanceInput, extra?: ConnectorExtra): StepSpec => connector("termii@1", "check_balance", input, extra),
  /** Send SMS (unsafe_write) */
  send_sms: (input: TermiiSendSmsInput, extra?: ConnectorExtra): StepSpec => connector("termii@1", "send_sms", input, extra),
};

/** Connector refs with helpers here, for code generation. */
export const CONNECTOR_HELPERS: Record<string, string> = {
  "dojah@1": "dojah",
  "iswallet@1": "iswallet",
  "paystack@1": "paystack",
  "postgres@1": "postgres",
  "termii@1": "termii",
};
