// Command sdkgen writes sdk/src/connectors.gen.ts: typed step helpers for
// the connectors built into the binary, so flow code reads
// iswallet.transfer({...}) and editors check the inputs. Run it with
// `go generate ./sdk` after changing a manifest; a test fails if the file
// is stale.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/israel-duff/taskiem/connectors/builtin"
	"github.com/israel-duff/taskiem/engine/connector"
)

func main() {
	out := "src/connectors.gen.ts"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	src, err := Generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, "sdkgen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(out, src, 0o644); err != nil { //nolint:gosec // a source file
		fmt.Fprintln(os.Stderr, "sdkgen:", err)
		os.Exit(1)
	}
}

var nonIdent = regexp.MustCompile(`[^A-Za-z0-9_]`)

// Generate renders the helpers module.
func Generate() ([]byte, error) {
	reg := connector.NewRegistry()
	if err := builtin.Register(reg, builtin.Options{}); err != nil {
		return nil, err
	}
	conns := reg.List()
	sort.Slice(conns, func(i, j int) bool { return conns[i].Ref() < conns[j].Ref() })
	var b bytes.Buffer
	b.WriteString("// Generated by tools/sdkgen from the connector manifests built into taskiem.\n// Do not edit: run `go generate ./sdk` instead.\n\n")
	b.WriteString("import { connector, type ConnectorExtra, type StepSpec, type Val, type Value } from \"./builder.js\";\n")
	helpers := map[string]string{}
	actionsOf := map[string][]string{}
	for _, c := range conns {
		ref := c.Ref()
		name := nonIdent.ReplaceAllString(c.Manifest.ID, "_")
		if major := strings.TrimPrefix(ref, c.Manifest.ID+"@"); major != "1" {
			name += "_v" + major
		}
		helpers[ref] = name
		fmt.Fprintf(&b, "\n// %s (%s)\n", c.Manifest.Name, ref)
		actions := make([]string, 0, len(c.Manifest.Actions))
		for a := range c.Manifest.Actions {
			actions = append(actions, a)
		}
		sort.Strings(actions)
		actionsOf[ref] = actions
		type entry struct {
			action, iface, doc string
			optional           bool
		}
		var entries []entry
		for _, a := range actions {
			spec := c.Manifest.Actions[a]
			iface := typeName(name) + typeName(a) + "Input"
			fields, optional, err := inputFields(spec.Input)
			if err != nil {
				return nil, fmt.Errorf("%s %s: %w", ref, a, err)
			}
			fmt.Fprintf(&b, "export interface %s {\n%s}\n", iface, fields)
			doc := spec.Title
			if doc == "" {
				doc = a
			}
			entries = append(entries, entry{a, iface, fmt.Sprintf("%s (%s)", doc, spec.Class), optional})
		}
		fmt.Fprintf(&b, "export const %s = {\n", name)
		for _, e := range entries {
			q := ""
			if e.optional {
				q = "?"
			}
			fmt.Fprintf(&b, "  /** %s */\n  %s: (input%s: %s, extra?: ConnectorExtra): StepSpec => connector(%q, %q, input, extra),\n",
				strings.ReplaceAll(e.doc, "*/", "* /"), e.action, q, e.iface, ref, e.action)
		}
		b.WriteString("};\n")
	}
	refs := make([]string, 0, len(helpers))
	for r := range helpers {
		refs = append(refs, r)
	}
	sort.Strings(refs)
	b.WriteString("\n/** Connector refs with helpers here, for code generation. */\nexport const CONNECTOR_HELPERS: Record<string, string> = {\n")
	for _, r := range refs {
		fmt.Fprintf(&b, "  %q: %q,\n", r, helpers[r])
	}
	b.WriteString("};\n")
	b.WriteString("\n/** The actions each helper has: any other action is generated as connector(...). */\nexport const CONNECTOR_ACTIONS: Record<string, readonly string[]> = {\n")
	for _, r := range refs {
		q := make([]string, len(actionsOf[r]))
		for i, a := range actionsOf[r] {
			q[i] = strconv.Quote(a)
		}
		fmt.Fprintf(&b, "  %q: [%s],\n", r, strings.Join(q, ", "))
	}
	b.WriteString("};\n")
	return b.Bytes(), nil
}

func typeName(s string) string {
	var out strings.Builder
	for _, p := range strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' }) {
		out.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return out.String()
}

// inputFields renders an action's input schema's properties as interface
// fields; optional reports whether the whole input may be omitted.
func inputFields(raw json.RawMessage) (string, bool, error) {
	if len(raw) == 0 {
		return "  [key: string]: Value;\n", true, nil
	}
	var s struct {
		Properties map[string]map[string]any `json:"properties"`
		Required   []string                  `json:"required"`
	}
	if err := json.Unmarshal(raw, &s); err != nil {
		return "", false, err
	}
	req := map[string]bool{}
	for _, r := range s.Required {
		req[r] = true
	}
	names := make([]string, 0, len(s.Properties))
	for n := range s.Properties {
		names = append(names, n)
	}
	sort.Strings(names)
	var b strings.Builder
	for _, n := range names {
		p := s.Properties[n]
		if d, ok := p["description"].(string); ok && d != "" {
			fmt.Fprintf(&b, "  /** %s */\n", strings.ReplaceAll(d, "*/", "* /"))
		}
		opt := "?"
		if req[n] {
			opt = ""
		}
		key := n
		if nonIdent.MatchString(n) {
			key = fmt.Sprintf("%q", n)
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", key, opt, tsType(p))
	}
	if len(names) == 0 {
		b.WriteString("  [key: string]: Value;\n")
	}
	return b.String(), len(s.Required) == 0, nil
}

func tsType(p map[string]any) string {
	if enum, ok := p["enum"].([]any); ok && len(enum) > 0 {
		parts := make([]string, len(enum))
		for i, e := range enum {
			j, _ := json.Marshal(e)
			parts[i] = string(j)
		}
		return "Val<" + strings.Join(parts, " | ") + ">"
	}
	switch p["type"] {
	case "string":
		return "Val<string>"
	case "integer", "number":
		return "Val<number>"
	case "boolean":
		return "Val<boolean>"
	}
	return "Value" // objects and lists: literals or expressions at any depth
}
