package slo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"strconv"

	"sigs.k8s.io/yaml"
)

// Rule is a Prometheus recording or alerting rule.
type Rule struct {
	Record      string            `json:"record,omitempty"`
	Alert       string            `json:"alert,omitempty"`
	Expr        string            `json:"expr"`
	For         string            `json:"for,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// Group is a rule group.
type Group struct {
	Name     string `json:"name"`
	Interval string `json:"interval,omitempty"`
	Rules    []Rule `json:"rules"`
}

// RuleFile is a Prometheus rule file (and a PrometheusRule's spec).
type RuleFile struct {
	Groups []Group `json:"groups"`
}

// ratio prints a number without float noise (1 - 0.999 is 0.001).
func ratio(f float64) string { return strconv.FormatFloat(math.Round(f*1e9)/1e9, 'f', -1, 64) }

// Rules builds the rule file.
func Rules() RuleFile {
	rec := Group{Name: "taskiem-slo-recording", Interval: "30s"}
	for _, s := range SLOs {
		for _, w := range Windows {
			rec.Rules = append(rec.Rules, Rule{Record: Record(w), Expr: s.ErrorRatio(w),
				Labels: map[string]string{"slo": s.Name}})
		}
		// The share of the 30-day error budget left, from hourly ratios (an
		// unweighted average: quiet hours count as much as busy ones).
		rec.Rules = append(rec.Rules,
			Rule{Record: "taskiem:slo_target:ratio", Expr: ratio(s.Target), Labels: map[string]string{"slo": s.Name}},
			Rule{Record: "taskiem:slo_errors:ratio_avg" + Period,
				Expr:   fmt.Sprintf(`avg_over_time(%s{slo=%q}[%s])`, Record("1h"), s.Name, Period),
				Labels: map[string]string{"slo": s.Name}},
			Rule{Record: "taskiem:slo_error_budget_remaining:ratio",
				Expr:   fmt.Sprintf(`1 - taskiem:slo_errors:ratio_avg%s{slo=%q} / %s`, Period, s.Name, ratio(1-s.Target)),
				Labels: map[string]string{"slo": s.Name}})
	}
	alerts := Group{Name: "taskiem-slo-alerts"}
	for _, s := range SLOs {
		budget := 1 - s.Target
		for _, b := range Burns {
			threshold := ratio(b.Rate) + " * " + ratio(budget)
			alerts.Rules = append(alerts.Rules, Rule{
				Alert: s.Alert,
				Expr: fmt.Sprintf("%s{slo=%q} > (%s)\nand\n%s{slo=%q} > (%s)",
					Record(b.Long), s.Name, threshold, Record(b.Short), s.Name, threshold),
				Labels: map[string]string{"severity": b.Severity, "slo": s.Name, "window": b.Long},
				Annotations: map[string]string{
					"summary":     fmt.Sprintf("%s is burning its error budget %sx too fast (%s and %s windows)", s.Title, ratio(b.Rate), b.Long, b.Short),
					"description": fmt.Sprintf("%s Objective: %s%% over %s. At this rate the whole budget lasts %s.", s.Description, ratio(s.Target*100), Period, lasts(b.Rate)),
					"runbook_url": RunbookURL(s.Alert),
				},
			})
		}
	}
	other := Group{Name: "taskiem-alerts"}
	for _, a := range Alerts {
		other.Rules = append(other.Rules, Rule{Alert: a.Name, Expr: a.Expr, For: a.For,
			Labels:      map[string]string{"severity": a.Severity},
			Annotations: map[string]string{"summary": a.Summary, "description": a.Description, "runbook_url": RunbookURL(a.Name)}})
	}
	return RuleFile{Groups: []Group{rec, alerts, other}}
}

func lasts(rate float64) string {
	days := 30 / rate
	if days >= 1 {
		return ratio(float64(int(days*10+0.5))/10) + " days"
	}
	return strconv.Itoa(int(days*24+0.5)) + " hours"
}

// RulesYAML is the rule file as committed under deploy/prometheus.
func RulesYAML() ([]byte, error) {
	b, err := yaml.Marshal(Rules())
	if err != nil {
		return nil, err
	}
	head := "# Generated by go generate ./engine/slo from engine/slo/slo.go. Do not edit.\n" +
		"# Taskiem's SLOs (docs/reliability.md, decision 0023): recording rules and\n" +
		"# multi-window, multi-burn-rate alerts. Load into Prometheus as a rule file,\n" +
		"# or enable prometheusRule in the Helm chart.\n"
	return append([]byte(head), b...), nil
}

// Dashboard is the Grafana dashboard for the SLOs and error budgets.
func Dashboard() ([]byte, error) {
	type target struct {
		Expr         string `json:"expr"`
		LegendFormat string `json:"legendFormat,omitempty"`
		RefID        string `json:"refId"`
	}
	type gridPos struct{ H, W, X, Y int }
	ds := map[string]string{"type": "prometheus", "uid": "${datasource}"}
	var panels []map[string]any
	id := 0
	add := func(kind, title, desc, unit string, pos gridPos, targets []target, extra map[string]any) {
		id++
		p := map[string]any{
			"id": id, "type": kind, "title": title, "description": desc, "datasource": ds,
			"gridPos":     map[string]int{"h": pos.H, "w": pos.W, "x": pos.X, "y": pos.Y},
			"targets":     targets,
			"fieldConfig": map[string]any{"defaults": map[string]any{"unit": unit}, "overrides": []any{}},
		}
		for k, v := range extra {
			p[k] = v
		}
		panels = append(panels, p)
	}
	row := func(title string, y int) {
		id++
		panels = append(panels, map[string]any{"id": id, "type": "row", "title": title, "collapsed": false,
			"gridPos": map[string]int{"h": 1, "w": 24, "x": 0, "y": y}, "panels": []any{}})
	}
	y := 0
	for _, s := range SLOs {
		row(fmt.Sprintf("%s (objective %s%%)", s.Title, ratio(s.Target*100)), y)
		y++
		sel := fmt.Sprintf(`{slo=%q}`, s.Name)
		add("stat", "SLI, last 30 days", s.Description, "percentunit", gridPos{6, 6, 0, y},
			[]target{{Expr: "1 - taskiem:slo_errors:ratio_avg" + Period + sel, RefID: "A"}},
			map[string]any{"options": map[string]any{"reduceOptions": map[string]any{"calcs": []string{"lastNotNull"}}, "colorMode": "value"}})
		add("stat", "Error budget left", "Share of the 30-day error budget not yet spent.", "percentunit", gridPos{6, 6, 6, y},
			[]target{{Expr: "taskiem:slo_error_budget_remaining:ratio" + sel, RefID: "A"}},
			map[string]any{"options": map[string]any{"reduceOptions": map[string]any{"calcs": []string{"lastNotNull"}}, "colorMode": "background"},
				"fieldConfig": map[string]any{"defaults": map[string]any{"unit": "percentunit", "min": 0, "max": 1,
					"thresholds": map[string]any{"mode": "absolute", "steps": []map[string]any{{"color": "red", "value": nil}, {"color": "orange", "value": 0.25}, {"color": "green", "value": 0.5}}}},
					"overrides": []any{}}})
		var burn []target
		for i, w := range []string{"1h", "6h", "1d"} {
			burn = append(burn, target{Expr: fmt.Sprintf("%s%s / %s", Record(w), sel, ratio(1-s.Target)), LegendFormat: "burn rate " + w, RefID: string(rune('A' + i))})
		}
		add("timeseries", "Burn rate", "1 spends the budget exactly over 30 days; 14.4 over an hour pages.", "none", gridPos{6, 12, 12, y}, burn, nil)
		y += 6
	}
	row("Canary and queues", y)
	y++
	add("timeseries", "Canary probes", "Synthetic end-to-end probes by result.", "short", gridPos{8, 8, 0, y},
		[]target{{Expr: "sum by (result) (increase(taskiem_canary_probes_total[5m]))", LegendFormat: "{{result}}", RefID: "A"}}, nil)
	add("timeseries", "Canary latency (p50, p95)", "Webhook accepted, and send to finished run.", "s", gridPos{8, 8, 8, y},
		[]target{
			{Expr: "histogram_quantile(0.5, sum by (le, phase) (rate(taskiem_canary_duration_seconds_bucket[15m])))", LegendFormat: "p50 {{phase}}", RefID: "A"},
			{Expr: "histogram_quantile(0.95, sum by (le, phase) (rate(taskiem_canary_duration_seconds_bucket[15m])))", LegendFormat: "p95 {{phase}}", RefID: "B"},
		}, nil)
	add("timeseries", "Oldest ready task", "Age of the oldest task waiting in each queue.", "s", gridPos{8, 8, 16, y},
		[]target{{Expr: "max by (queue) (taskiem_queue_oldest_ready_seconds)", LegendFormat: "{{queue}}", RefID: "A"}}, nil)
	y += 8
	add("timeseries", "Step dispatch delay (p95)", "Spec 15.3: under 50 ms.", "s", gridPos{8, 8, 0, y},
		[]target{{Expr: "histogram_quantile(0.95, sum by (le, queue) (rate(taskiem_step_dispatch_delay_seconds_bucket[5m])))", LegendFormat: "{{queue}}", RefID: "A"}}, nil)
	add("timeseries", "Run start (p50, p99)", "Trigger accepted to first worker step claimed.", "s", gridPos{8, 8, 8, y},
		[]target{
			{Expr: "histogram_quantile(0.5, sum by (le) (rate(taskiem_run_start_seconds_bucket[5m])))", LegendFormat: "p50", RefID: "A"},
			{Expr: "histogram_quantile(0.99, sum by (le) (rate(taskiem_run_start_seconds_bucket[5m])))", LegendFormat: "p99", RefID: "B"},
		}, nil)
	add("timeseries", "Scheduler lateness (p99)", "How late timers and schedules fire.", "s", gridPos{8, 8, 16, y},
		[]target{{Expr: "histogram_quantile(0.99, sum by (le, kind) (rate(taskiem_scheduler_lateness_seconds_bucket[5m])))", LegendFormat: "{{kind}}", RefID: "A"}}, nil)

	d := map[string]any{
		"title": "Taskiem SLOs", "uid": "taskiem-slo", "schemaVersion": 39, "version": 1, "editable": true,
		"tags": []string{"taskiem", "slo"}, "timezone": "utc", "refresh": "1m",
		"time":        map[string]string{"from": "now-7d", "to": "now"},
		"description": "Generated by go generate ./engine/slo (docs/reliability.md). Do not edit by hand.",
		"templating": map[string]any{"list": []map[string]any{{
			"name": "datasource", "type": "datasource", "query": "prometheus", "label": "Prometheus",
			"current": map[string]any{}, "hide": 0, "refresh": 1,
		}}},
		"annotations": map[string]any{"list": []any{}},
		"panels":      panels,
	}
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(d); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// Files are the generated files, by path from the repository root.
func Files() (map[string][]byte, error) {
	rules, err := RulesYAML()
	if err != nil {
		return nil, err
	}
	dash, err := Dashboard()
	if err != nil {
		return nil, err
	}
	tests, err := RulesTestYAML()
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		"deploy/prometheus/taskiem-rules.test.yaml":        tests,
		"deploy/prometheus/taskiem-rules.yaml":             rules,
		"deploy/helm/taskiem/files/prometheus-rules.yaml":  rules,
		"deploy/grafana/taskiem-slo-dashboard.json":        dash,
		"deploy/helm/taskiem/files/grafana-dashboard.json": dash,
	}, nil
}
